N_ROBOTS = 10
DT = 0.05
MAX_SPEED = 0.55
SENSE_RADIUS = 2.2
ENCIRCLE_RADIUS = 1.4
TARGET_STANDOFF_DISTANCE = 0.7
ARENA_LIMIT = 4.0
STEPS = 1200

ROBOT_RADIUS = 0.12
ROBOT_COLLISION_DISTANCE = 2 * ROBOT_RADIUS
FLOCK_SEPARATION_DISTANCE = 0.55

USE_GENERATED_POLICY = True

SAVE_RUN_SUMMARY = True
RUN_SUMMARY_FILE = "run_summary.txt"

USE_LLM_GENERATOR = True
LLM_MODEL = "gemini-2.5-flash"
LLM_MAX_RETRIES = 2

SAVE_GENERATED_POLICY = True
GENERATED_POLICY_FILE = "generated_policy_latest.py"

USE_LLM_TASK_ANALYZER = True
TASK_ANALYZER_MAX_RETRIES = 2